### PR TITLE
Proposed fixes 1.13

### LINKED ISSUE #1070: Feature request: persicope: support https://www.periscope.tv/username/broadcastID
Periscope has expanded their web viewer to allow for limited browsing, and have also shifted away from having the token in the URL.

Example 1: https://www.periscope.tv/cheersfelicia/1yNxaoapngvGj
Example 2: https://www.periscope.tv/w/1yNxaoapngvGj

(Note: these were found by going to the publicly accessible couch mode. If there's any indication that the linked broadcast is not meant to be public, the links can be removed)

### LINKED ISSUE #1122: Plugin Ustream.tv not working
As you can see this live stream on Ustream platform is not opening with Livestreamer. 

<code>livestreamer "http://www.ustream.tv/channel/tv-sandzak" best
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/tv-sandzak
[plugin.ustreamtv][error] Unable to fetch desktop streams: Unable to validate re
sult: Unable to validate key 'stream': Unable to validate result: Unable to vali
date key 'streams': Unable to validate result: Type of ScriptDataReference(refer
ence=7) should be 'dict' but is 'ScriptDataReference' or Type of ScriptDataRefer
ence(reference=7) should be 'list' but is 'ScriptDataReference' or [ScriptDataOb
ject([(u'name', u'uhs_tcdn'), (u'url', u'http://uhs-live-default.ustream.tv/ams-
uhs01/streams/httpflv/ustreamVideo/18684284/'), (u'streams', [ScriptDataObject([
(u'chunkTime', 5000.0), (u'offsetInMs', 4821.0), (u'chunkRange', ScriptDataObjec
t([(u'1447230451', u'958283629'), (u'1447230461', u'1943747493')])), (u'offset',
 433.0), (u'width', 600.0), (u'bitrate', 537.0), (u'counter', -1.0), (u'streamNa
me', u'streams/live_1_%_%.flv'), (u'chunkId', 1447230458.0), (u'videoCodec', u'H
264'), (u'height', 480.0)])])]), ScriptDataObject([(u'name', u'uhs_akamai'), (u'
varnishUrl', u'http://uhs-akamai.ustream.tv/ams/ams-uhs01/streams/httpflv/ustrea
mVideo/18684284/'), (u'url', u'http://uhs-akamai.ustream.tv/ams/ams-uhs01/stream
s/httpflv/ustreamVideo/18684284/'), (u'streams', ScriptDataReference(reference=7
))]), ScriptDataObject([(u'name', u'uhs_highwinds'), (u'varnishUrl', u'http://uh
s-highwinds.ustream.tv/ams/ams-uhs01/streams/httpflv/ustreamVideo/18684284/'), (
u'url', u'http://uhs-highwinds.ustream.tv/ams/ams-uhs01/streams/httpflv/ustreamV
ideo/18684284/'), (u'streams', ScriptDataReference(reference=7))])] does not equ
al 'offline'
error: No streams found on this URL: http://www.ustream.tv/channel/tv-sandzak</code>

Any chance for a fix ?

### LINKED ISSUE #1171: ustream.py has error on  update_chunk_info
running the following command on a raspberry pi:
livestreamer http://www.ustream.tv/channel/xfm-kenya best --p                                                                                                                                                           layer omxplayer --fifo

gives the output:

[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/xfm-kenya
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (uhs)
Traceback (most recent call last):
  File "/usr/local/bin/livestreamer", line 9, in <module>
    load_entry_point('livestreamer==1.12.2', 'console_scripts', 'livestreamer')()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 886, in main
    handle_url()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 491, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 378, in handle_stream
    success = output_stream(stream)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 245, in output_stream
    stream_fd, prebuffer = open_stream(stream)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py", line 222, in open_stream
    stream_fd = stream.open()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ustreamtv.py", line 403, in open
    reader.open()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/stream/segmented.py", line 185, in open
    self.worker = self.__worker__(self)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ustreamtv.py", line 257, in __init__
    self.process_module_info()
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ustreamtv.py", line 310, in process_module_info
    self.update_chunk_info(stream)
  File "/usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ustreamtv.py", line 319, in update_chunk_info
    chunk_range = dict(map(partial(map, int), chunk_range.items()))
ValueError: invalid literal for int() with base 10: 'dc14dae661'

### LINKED ISSUE #1218: streamupcom.py plugin not working
AttributeError: 'NoneType' object has no attribute 'group'

### LINKED ISSUE #1272: livestream.com stop working
Live streams form livestream.com are not working.

Ej. http://livestream.com/accounts/17275479/events/4945175

You get the following error:

[cli][error] Could not open stream: Unable to open URL: http://viewerplus.livestream.com/assets/swf/hdplayer-2.0-viewerplus.swf (404 Client Error: Not Found for url: http://viewerplus.livestream.com/assets/swf/hdplayer-2.0-viewerplus.swf)

### LINKED ISSUE #1306: Twitch Oauth not possible due to 404
Hi,

you cannot authenticate with Twitch, since the URL isn't reachable anymore and errors out with 404.

The URL without my Twitch-Token:
http://livestreamer.tanuki.se/en/develop/twitch_oauth.html#access_token=*token*&scope=user_read+user_subscriptions

### LINKED ISSUE #1360: Need help to fix Douyutv
Im new to this and i don't know how to fix this
image
some one please help me :(

### LINKED ISSUE #1370: Vaughnlive plugin response length validation
There seems to be an issue with the Vaughnlive plugin

Similar problem was described at #897 / #904 , but the recommended fix no longer works. 

$ livestreamer http://vaughnlive.tv/stream best
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/stream
error: Unable to validate response text: Minimum length is 2 but value is 1
$

Unfortunately I am not very adept with python at this stage.. :( Pls help! :)

### LINKED ISSUE #1374: AfreecaTV service changed,plugin fixed.
change afreeca.py
from
`CHANNEL_INFO_URL = "http://live.afreeca.com:8057/api/get_broad_state_list.php"`
to
`CHANNEL_INFO_URL = "http://live.afreecatv.com:8057/api/get_broad_state_list.php"`

### LINKED ISSUE #1396: Something changed at twitch?
error: No streams found on this URL: https://www.twitch.tv/dansgaming/v/77825368

### PR DESCRIPTION
**Pull request by javiercantero**
This is a compilation of 19 pending pull requests by 18 contributors to
be applied to the lastest version of chrippa's develop branch (commit
ab80dbd on 2 Feb 2016) in order to fix 14 plugins of livestreamer. It
neither includes new code nor new plugins, only fixes to existing
plugins.
- Twitch.tv fixes:
  - Update redirect URI after successful twitch oauth (PR #1359 by
    @mindhalt) (Fixes: #1306 #1341 #1385)
  - Fix Twitch plugin not working (PR #1397 by @e00E) (Fixes: #1396)
  - Fixed weighting of Twitch stream names (PR #1429 by @mjbcopland)
    (Fixes: #1433)
  - Use client ID for twitch.tv API calls (PR #1483 by @LoneFox78)
    (Fixes: #1407 #1456 #1478)
- livestream.com fixes:
  - plugins.livestream: Update for API changes (PR #1277 by @intact)
    (Fixes: #1272 #1318 #1422 #1465)
- ustream.tv fixes:
  - ustream: fix desktop stream validation (PR #1227 by @pmrowla)
    (Fixes: #1122)
  - Fix issue #1276 - ustream.tv KeyError: 'url' (PR #1278 —except
    merge commit— by @bvklim and @snifer1981) (Fixes: #1171 #1226
    #1276 #1388 #1389 #1415)
- afreeca fixes:
  - plugins.afreeca: fix stream (PR #1383 by @dsokal)
  - channel info url change in afreeca plugin (PR #1401 by
    @AleXoundOS) (Fixes #1374 #1416)
- Other plugins fixes:
  - plugins.streamupcom: API changes (PR #1206 by @406NotAcceptable)
    (Fixes: #1218 #1256 #1293)
  - plugins.tga: Support more streams (PR #1289 by @intact) (Fixes:
    #1208 #1285 #1344)
  - Change url schema to match changes at periscope (PR #1302 by
    @michaelnachname) (Fixes: #1070 #1175)
  - plugins.nrk: Updated for webpage changes. (PR #1352 by @sn4kebite)
  - Plugin SVTPlay: Add API support (PR #1375 by @tboss) (Fixes:
    #1258)
  - plugins.vaughnlive: Update for API changes (PR #1376 by @intact)
    (Fixes: #1370 #1373 #1379 #1413 #1443 #1445  #1497)
  - update douyu (PR #1414 by @steven7851) (Fixes: #1360 #1411 #1463)
  - livecodingtv: Refactoring and update for the VOD support (PR #1450
    by @int3l)
  - update goodgame (PR #1461 by @liz1rgin) (Fixes: #1460)
  - Picarto plugin: update RTMPStream settings (PR #1469 by @Swirt)
    (Fixes: #1419 #1468)

### CODE REVIEW

**Comment by sbstp** [comment]
@javiercantero could you open this PR in streamlink? We'd be happy to take those fixes.

**Comment by javiercantero** [comment]
@sbstp Seems that the GitHub interface doesn't allow me to create a PR from my repo to the streamlink repo.

Edit: the problem is that the streamlink repository is not listed as a fork of livestreamer. Have you guys pushed it directly from a local git repo instead of using the GH fork button?

**Comment by Erk-** [comment]
You could try somethin from this site @javiercantero http://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories

**Comment by javiercantero** [comment]
@Erk- Finally I've done it by forking the streamlink repository and using the forked repo as a proxy.

But there is a serious divergence between the streamlink branch (based on chrippa's master branch) and mine (based on chrippa's develop branch). And try to merge these branches is going to be a PITA /cc @sbstp

**Comment by vadosnaprimer** [comment]
Can you post a build in case this will never be seen by the author?

**Comment by javiercantero** [comment]
@vadosnaprimer A build like executables for Win/Mac? I can't, I don't use any of those environments.

**Comment by mjbcopland** [comment]
Running `win32/build-with-bootstrap.sh` produces the following build:
- [livestreamer-v1.13rc-win32-setup.exe](https://mega.nz/#!PEVzkRTS!0WhVhaTUl-3tHpAJ84_3Y_H6itZJqKWD3Ue5Z5FGJco)
- [livestreamer-v1.13rc-win32.zip](https://mega.nz/#!bYcXlKyK!IJnUYQ3RPk9_HwTI7b5lWVd0G3yXLmSwGLlGEfkQrUM)

If you're not on Windows, I believe you should be able to build and install yourself using `python setup.py install`.

**Comment by Kiingy** [comment]
Sorry for being a noob, but can anyone tell me how I install these fixes?

**Comment by Erk-** [comment]
@NuMs1 You should look at [Streamlink](https://github.com/streamlink/streamlink) which is a fork of livestreamer.

**Comment by javiercantero** [comment]
@NuMs1 If you are asking about using it in Windows, in the @mjbcopland's message just above your comment there is a build ready to install. But as @Erk- has pointed out,  it's better if you use the new project [Streamlink](https://github.com/streamlink/streamlink) since it's maintained.

**Comment by msikma** [comment]
Unfortunately `vaughnlive` is still broken, despite an effort to fix it. I'll try to have a look at it later. It claims the following:

```
[cli][info] Found matching plugin vaughnlive for URL <url>
error: Unable to validate response text: Minimum length is 3 but value is 1
```

edit: It seems that more research is needed to get an appropriate response from the server to fix this. It seems to make an appropriate call but then somewhere in the plugin it makes an HTTP call that has an empty body and response 200. That's where it breaks, since it expects a body with more required data.

edit 2: turns out it's a super quick fix. In `src/livestreamer/plugins/vaughnlive.py`:

* change `INFO_URL` to `"http://mvn.vaughnsoft.net/video/edge/mnt-{domain}_{channel}?{version}_{ms}-{ms}-{random}"`
* optionally, add one line to the `_url_re` to make it the following:
```
_url_re = re.compile("""
    http(s)?://(\w+\.)?
    (?P<domain>vaughnlive|breakers|instagib|vapers).tv
    (/embed/video)?
    /(?P<channel>[^/&?]+)
 """, re.VERBOSE)
```
This allows URLs from embeds to work as well.

This is a quick fix to get vaughnlive working again. The seem to continuously change the first few letters in minor ways to throw streaming software off.

**Comment by bozhodimitrov** [comment]
Request for closing this one. Seems to be a leftover.

**Comment by javiercantero** [comment]
Ok. @int3l, closing it.

**Pull request closed without merging**
