### PR TITLE
Added plugin for Kanal 5, Kanal 9 and Kanal 11.

### PR DESCRIPTION
**Pull request by tboss**
Works well for VODs, but live streams may or may not work (will test once available).

### CODE REVIEW

**Comment by chrippa** [comment]
Thanks!

**Comment by drejjmit** [comment]
Kanal 5, Kanal 9 and Kanal 11 renamed dplay.se. Will you be adding support for that?

**Comment by tboss** [comment]
I took a quick look at the new platform about a week ago, but haven't been able to find any API or such. Did a disassembly on the swf-files but it hasn't yielded anything fruitful so far. Also it is likely that the streams are DRM-protected now, which of course would prevent using livestreamer with it. Though if I manage to find a solution, I'll be sure to post it.

**Comment by rendom** [comment]
https://github.com/spaam/svtplay-dl/blob/master/lib/svtplay_dl/service/dplay.py

**Comment by drejjmit** [comment]
Well there's a start. Will anyone try to make it livestreamer compatible?

**Comment by drejjmit** [comment]
This plugin no longer works.

**Comment by tboss** [comment]
As you may have noticed I've created a pull request (currently awaiting review/commit from chrippa) for a plugin based on Dplay. If you want you can try it out by downloading and placing the dplay.py in the standalone plugins folder, see http://docs.livestreamer.io/cli.html#sideloading-plugins .

**Comment by drejjmit** [comment]
[plugin.dplay][error] Failed to extract HDS streams: This manifest requires the 'pvswf' parameter to verify the SWF

Anything to worry about? Looks like it downloads correctly.

Edit: Doesn't get it on newer shows. Try this one if you wanna see it yourself: [http://www.dplay.se/100-hojdare/season-6-pojken-som-aldrig-vill-bli-stor/](http://www.dplay.se/100-hojdare/season-6-pojken-som-aldrig-vill-bli-stor/)

**Comment by tboss** [comment]
Thanks, I'll have a look at it. It concerns only the HDS streams as it appears -- the HLS streams seem to parse and download just fine.

**Comment by tboss** [comment]
Just pushed a new commit to fix the issue. If the swf url is found to be changing, I'll make a more failsafe fix (parse from input page).

**Comment by drejjmit** [comment]
It stopped working. "error: No streams found on this URL" on everything i try to download.

Edit:
Fixed with this edit: Line 97

```
        if not match:
            match = re.search(r'data-video-id="([^"]+)"', res)
            if not match:
                return {}   # Return if shortlink/video ID not found
        videoId = match.group (1)
```

**Comment by tboss** [comment]
Yes, it seems they've changed the location of the video id, simple fix as you've also discovered. I'll push the fix asap. I should probably also make it so that error states report something useful (output error message or yield proper error), but also don't know what chrippa's take is on this.

**Pull request merged**
