### PR TITLE
ustream: fix desktop stream validation

### PR DESCRIPTION
**Pull request by pmrowla**
- The validation changes in #1126 aren't strict enough, there are now
  more than 1 unexpected streams that we can't read, and they do not all
  contain the varnishUrl key.

### CODE REVIEW

**Comment by pmrowla** [comment]
I think this should also fix whatever the problem was in #1226 although I wasn't able to reproduce the issue for that ustream URL (http://www.ustream.tv/siliconangle)

should also resolve remaining the non-windows specific problems in #1122

**Comment by maki-chan** [comment]
Works great for me, thanks for the patch (tested it locally)

**Comment by torbjorntorbjorn** [comment]
Works for me as well. Thank you, @pmrowla.

**Comment by pmrowla** [comment]
no point in keeping this open

**Pull request closed without merging**
